### ISSUE TITLE
EagleCAD Dateien

### ISSUE THREAD

**Issue by lambda1103** [Cytrill/hrdwr#1]
Wäre ganz schön die EagleCAD-Dateien öffentlich zu machen. So könnte ich vielleicht ein paar zum Testen von Spieleentwürfen produzieren lassen.

**Comment by heyjuvi** [comment]
Habe das mal an entsprechende Personen weiterkommuniziert. Steht eigentlich schon länger auf der Agenda, aber irgendwie haben wir das immer wieder verschludert.

**Comment by simon-budig** [comment]
Ich habe da mal was gepusht...

**Comment by lambda1103** [comment]
Vielen Dank

**Comment by heyjuvi** [comment]
Aber schau nochmal drüber, die Version ist vielleicht noch fehlerhaft, es fehlten in der unserer produzierten Version nämlich noch ein paar Vorwiderstände.
